### ISSUE TITLE
Feature Request: Remove unused imports

### ISSUE THREAD

**Issue by jgarte** [pflanze/anysexpr#1]
Would it be out of scope for this project to remove unused imports from Guile/Guix code?

**Comment by pflanze** [comment]
The use of the anysexpr crate as the parser and printer for such a program is definitely in scope. It's already possible to parse white space and comments, and those could be saved back into the resulting file thus only causing the desired changes, even without a need for pretty-printing (which itself isn't implemented yet). Note that Guile syntax isn't fully implemented yet, but support is planned.

The actual program to carry out the change would not be in scope. The scope of anysexpr is only the s-expression syntax, the "surface-level" of lisp syntax. Lexical analysis, macro expansion, and module syntax interpretation are not in scope. You might do a quick and dirty job without these but avoiding any edge cases would probably require implementing the macro system and possibly a full Guile-compatible interpreter.

So, because of the way your feature request is formulated, I'm closing this issue. If however you go forward with implementing the program and are missing bits in anysexpr, I encourage you to open new issues with the particular bits you need.

**Comment by jgarte** [comment]
Thanks for the explanations! Makes sense. I'll keep these points in mind when further scoping out my use cases for `anysexpr`.
